name: cuidapet_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  dotenv: ^4.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: 
  injectable_generator: 
  shelf_router_generator: 
  pedantic: ^1.10.0
